const ListaProductos = [
    {
        id:1,
        title:'Cajón divisiones madera natural',
        price:2999,
        photo:'https://images-na.ssl-images-amazon.com/images/I/81tqBQGCvtL._AC_SL1500_.jpg',
        stock:7,
        discount:'20% OFF',
        category_name:'cocina',
    },
    {
        id:2,
        title:'Portavelas de madera de montaje en pared',
        price:4799,
        photo:'https://images-na.ssl-images-amazon.com/images/I/71BkRl9CMcL._AC_SL1500_.jpg',
        stock:3,
        discount:'25% OFF',
        category_name:'deco',
    },                
    {
        id:3,
        title:'Alfombra antideslizante para ducha bambú',
        price:3499,
        photo:'https://images-na.ssl-images-amazon.com/images/I/81f34yLfQgL._AC_SL1500_.jpg',
        stock:6,
        discount:'15% OFF',
        category_name:'bano',
    },
    {
        id:4,
        title:'Mesita de noche Home Styles Arts And Crafts',
        price:7499,
        photo:'https://images-na.ssl-images-amazon.com/images/I/71YOY0Emd3L._AC_SL1500_.jpg',
        stock:12,
        category_name:'dormitorio',
    },
    {
        id:5,
        title:'Tabla de corte John Boos Chop-N-Slice de 12 x 8 x 1 pulg, junta de corte profunda',
        price:2999,
        photo:'https://images-na.ssl-images-amazon.com/images/I/51o3JTlXGHL._AC_SL1024_.jpg',
        stock:4,
        discount:'20% OFF',
        category_name:'cocina',
    },
    {
        id:6,
        title:'Caja de papel de seda, Nuez, Marrón',
        price:4999,
        photo:'https://images-na.ssl-images-amazon.com/images/I/61Wolhmn7-L._AC_SL1000_.jpg',
        stock:8,
        category_name:'deco',
    },                
    {
        id:7,
        title:'Bandeja de bañera, organizador de baño bambú',
        price:2499,
        photo:'https://images-na.ssl-images-amazon.com/images/I/71MROI7Qb6L._AC_SL1500_.jpg',
        stock:20,
        discount:'12% OFF',
        category_name:'bano',
    },
    {
        id:8,
        title:'Lampara de lectura Tommons',
        price:5099,
        photo:'https://images-na.ssl-images-amazon.com/images/I/61XwZ541PqL._AC_SL1500_.jpg',
        stock:16,
        category_name:'dormitorio',
    },                            
]
export default ListaProductos;